# Generated by Django 6.1.1 on 2026-09-27 17:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_candidateprofile_is_verified_and_more'),
        ('employers', '0004_application_resume_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_ref', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('title', models.CharField(help_text='e.g., Inpatient Medical Coder - Remote', max_length=255)),
                ('contract_type', models.CharField(choices=[('HOURLY', 'Hourly (Weekly Timesheet)'), ('MILESTONE', 'Fixed Milestone / Deliverables')], default='HOURLY', max_length=20)),
                ('disbursement_mode', models.CharField(choices=[('OPTION_A', 'Option A: Direct Subaccount Split (Weekly Recurring)'), ('OPTION_B', 'Option B: Platform Escrow Pool (Milestone/Short-Term)')], default='OPTION_A', max_length=20)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net hourly rate paid to candidate ($)', max_digits=10)),
                ('kodafriq_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Kodafriq platform markup percentage (default 10.00%)', max_digits=5)),
                ('weekly_hour_limit', models.PositiveIntegerField(default=40, help_text='Maximum billable hours allowed per week')),
                ('total_milestone_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total fixed deliverable amount (for MILESTONE contract)', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Candidate Acceptance'), ('ACTIVE', 'Active / In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, help_text='Key deliverables, responsibilities, chart types, and clinical expectations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.candidateprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.employerprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='employers.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Net talent milestone compensation', max_digits=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid / Disbursed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('deliverable_file', models.FileField(blank=True, null=True, upload_to='contracts/milestones/')),
                ('submission_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employer_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(help_text='Monday of the timesheet week')),
                ('week_end_date', models.DateField(help_text='Sunday of the timesheet week')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (In Progress)'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved by Employer'), ('PAID', 'Paid / Settled'), ('DISPUTED', 'Disputed / Under Review')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_notes', models.TextField(blank=True, help_text='Weekly summary notes from talent to employer')),
                ('employer_review_notes', models.TextField(blank=True, help_text='Review feedback or adjustment comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='contracts.contract')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('contract', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Detailed explanation of disagreement or quality concern')),
                ('status', models.CharField(choices=[('OPEN', 'Open / Under Mediation'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Withdrawn / Cancelled')], default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Mediation notes and resolution details by Kodafriq Staff')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contracts.contract')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_disputes', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='contracts.milestone')),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='contracts.timesheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('charts_coded_count', models.PositiveIntegerField(default=0, help_text='Charts coded, claims audited, or cases handled')),
                ('work_description', models.TextField(blank=True, help_text='Clinical summary of tasks completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contracts.timesheet')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('timesheet', 'date')},
            },
        ),
    ]
