# Generated by Django 6.1.1 on 2026-09-19 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_category',
            field=models.CharField(choices=[('AUTH', 'Authentication & Security'), ('STAFF_ACTION', 'Staff Operation'), ('ADMIN_ACTION', 'Admin Control Panel'), ('VERIFICATION', 'Credential Verification'), ('SUSPENSION', 'Account Suspension'), ('SCORING', 'Score Weight Calibration'), ('MODERATION', 'Content Moderation'), ('DATA_EXPORT', 'Data Export'), ('SYSTEM', 'System Automated Event')], db_index=True, default='STAFF_ACTION', max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='http_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CERTIFICATE', 'Certificate Earned'), ('ASSESSMENT', 'Assessment Result'), ('SCORE_BOOST', 'Verified Score Update'), ('APPLICATION', 'Application Status'), ('JOB_MATCH', 'Job Opportunity'), ('SECURITY', 'Security & Account Notice'), ('SYSTEM', 'System Notice')], default='SYSTEM', max_length=30),
        ),
    ]
