# Generated by Django 6.1.1 on 2026-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_flaggedmessagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard Page Access Permission',
                'verbose_name_plural': 'Dashboard Page Access Permissions',
                'permissions': [('access_notifications', 'Can access staff notifications hub'), ('access_contracts', 'Can access client contracts docket'), ('access_disputes', 'Can access dispute mediation center'), ('access_payments', 'Can access payments & payouts command center'), ('access_automation', 'Can access scheduled automation engine'), ('access_analytics', 'Can access staff analytics & reports'), ('access_broadcasts', 'Can access broadcasts & alert center'), ('access_security_audit', 'Can access security telemetry & audit logs')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
