# Generated by Django 6.1.1 on 2026-10-03 05:39

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_candidateprofile_managers_and_more'),
        ('dashboard', '0006_staffdashboardaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDashboardAccessProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Dashboard Permission',
                'verbose_name_plural': 'Staff Dashboard Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='http_method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_entity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
