# Generated by Django 6.1.1 on 2026-09-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Kodafriq Weighting', max_length=100)),
                ('assessment_weight', models.DecimalField(decimal_places=2, default=40.0, help_text='Weight for assessments (default 40%)', max_digits=5)),
                ('work_performance_weight', models.DecimalField(decimal_places=2, default=25.0, help_text='Weight for work performance (default 25%)', max_digits=5)),
                ('training_weight', models.DecimalField(decimal_places=2, default=15.0, help_text='Weight for training completion (default 15%)', max_digits=5)),
                ('professional_experience_weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Weight for years of experience (default 10%)', max_digits=5)),
                ('readiness_weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Weight for professional readiness (default 10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('work_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('training_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('readiness_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='accounts.candidateprofile')),
            ],
        ),
    ]
