# Generated by Django 6.1.1 on 2026-09-12 18:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CANDIDATE', 'Healthcare Candidate'), ('EMPLOYER', 'Healthcare Employer'), ('ADMIN', 'Kodafriq Administrator')], default='CANDIDATE', help_text='Primary role on the platform', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='e.g., Inpatient Medical Coder | CPC, CCS Certified', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Professional bio & summary')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, help_text='e.g., Accra, Ghana / Remote', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('IMMEDIATE', 'Immediately Available'), ('TWO_WEEKS', '2 Weeks Notice'), ('ONE_MONTH', '1 Month Notice'), ('NOT_LOOKING', 'Currently Employed / Not Looking')], default='IMMEDIATE', max_length=30)),
                ('desired_salary_range', models.CharField(blank=True, max_length=100)),
                ('is_employer_ready', models.BooleanField(default=False, help_text='Indicates candidate has verified credentials and passed readiness check')),
                ('kodafriq_verified_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Dynamic weighted score from 0.00 to 100.00', max_digits=5)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='candidates/resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(help_text='e.g., CPC (Certified Professional Coder)', max_length=150)),
                ('issuing_organization', models.CharField(help_text='e.g., AAPC, AHIMA', max_length=150)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='candidates/certifications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(default='Healthcare & Revenue Cycle Management', max_length=120)),
                ('website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, help_text='e.g., 50-200 Employees', max_length=50)),
                ('contact_person_title', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='employers/logos/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved Healthcare Employer'), ('REJECTED', 'Application Declined')], default='PENDING', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.candidateprofile')),
            ],
        ),
    ]
