# Generated by Django 6.1.1 on 2026-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidateprofile_country_employerprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Overview of the organization, clinical focus, and culture.'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
