# Generated by Django 6.1.1 on 2026-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employerprofile_address_employerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates candidate has verified competency (passed skill assessments or staff-audited credentials)'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='is_employer_ready',
            field=models.BooleanField(default=False, help_text='Indicates candidate has verified credentials, required experience, and met employer readiness benchmarks'),
        ),
    ]
