# Generated by Django 6.1.1 on 2026-10-03 05:39

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidateprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidateprofile',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employerprofile',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
