# Generated by Django 6.1.1 on 2026-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_candidateprofile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='english_proficiency_proof',
            field=models.FileField(blank=True, help_text='Certificate or result scorecard proof of English proficiency', null=True, upload_to='candidates/assessments/english/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='english_proficiency_score',
            field=models.CharField(blank=True, help_text='Score, CEFR Level, or Grade (e.g., C1 Advanced, IELTS 7.5, TOEFL 100, EF SET 70/100)', max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='internet_speed_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internet Download Speed in Mbps', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='internet_speed_proof',
            field=models.FileField(blank=True, help_text='Screenshot or PDF proof of internet speed test (e.g. Speedtest.net, Fast.com)', null=True, upload_to='candidates/assessments/internet/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='internet_speed_upload_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internet Upload Speed in Mbps', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='typing_speed_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typing Accuracy percentage (e.g. 98.5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='typing_speed_proof',
            field=models.FileField(blank=True, help_text='Screenshot or certificate proof of typing speed test', null=True, upload_to='candidates/assessments/typing/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='typing_speed_wpm',
            field=models.PositiveIntegerField(blank=True, help_text='Typing Speed in Words Per Minute (WPM)', null=True),
        ),
    ]
