# Generated by Django 6.1.1 on 2026-09-27 19:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_candidateprofile_is_verified_and_more'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Kodafriq platform service markup percentage charged to employer (default 10.00%)', max_digits=5)),
                ('gateway_processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.90'), help_text='Payment gateway interchange pass-through fee (default 2.90%)', max_digits=5)),
                ('gateway_flat_fee', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Gateway flat fee per charge ($0.30)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Fee Configuration',
                'verbose_name_plural': 'Platform Fee Configurations',
            },
        ),
        migrations.CreateModel(
            name='CandidatePayoutProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_method', models.CharField(choices=[('PAYSTACK_MOMO', 'Paystack Mobile Money (Ghana GHS)'), ('FLUTTERWAVE_BANK', 'Flutterwave Bank Transfer (Pan-Africa)')], default='PAYSTACK_MOMO', max_length=30)),
                ('momo_network', models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('TELECEL', 'Telecel Cash (Vodafone)'), ('AT_MONEY', 'AT Money (AirtelTigo)')], default='MTN', max_length=20)),
                ('momo_phone_number', models.CharField(blank=True, help_text='e.g., +233241234567 or 0241234567', max_length=24)),
                ('momo_account_name', models.CharField(blank=True, help_text='Verified name as registered on Mobile Money account', max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_code', models.CharField(blank=True, help_text='Sort code or routing code', max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('bank_country', models.CharField(blank=True, default='Ghana', max_length=50)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Paystack Transfer Recipient Code (e.g. RCP_xxxx)', max_length=100)),
                ('flutterwave_subaccount_id', models.CharField(blank=True, help_text='Flutterwave Subaccount ID for split settlement', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Payout Profile',
                'verbose_name_plural': 'Candidate Payout Profiles',
            },
        ),
        migrations.CreateModel(
            name='ContractInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_ref', models.CharField(editable=False, max_length=32, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('talent_earnings', models.DecimalField(decimal_places=2, help_text='Guaranteed net compensation disbursed to candidate ($)', max_digits=10)),
                ('kodafriq_fee', models.DecimalField(decimal_places=2, help_text='10% Kodafriq platform service revenue ($)', max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment gateway pass-through interchange fee ($)', max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total employer billed amount ($)', max_digits=10)),
                ('payment_status', models.CharField(choices=[('DRAFT', 'Draft (Review Window)'), ('ISSUED', 'Issued / Pending Charge'), ('PROCESSING', 'Processing Gateway Charge'), ('SETTLED', 'Settled / Paid by Employer'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=20)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending Employer Settlement'), ('QUEUED', 'Queued for Upcoming Payout Run (Friday)'), ('PROCESSING', 'Processing Disbursement Transfer'), ('COMPLETED', 'Disbursed / Completed'), ('FAILED', 'Payout Failed'), ('ON_HOLD', 'On Hold / Disputed')], default='PENDING', max_length=20)),
                ('gateway_provider', models.CharField(choices=[('NONE', 'None / Manual'), ('FLUTTERWAVE', 'Flutterwave'), ('PAYSTACK', 'Paystack Ghana')], default='NONE', max_length=20)),
                ('gateway_charge_ref', models.CharField(blank=True, help_text='e.g. flw_tx_849204128', max_length=120)),
                ('gateway_payout_ref', models.CharField(blank=True, help_text='e.g. pstk_trf_9921045', max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract')),
                ('milestone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='contracts.milestone')),
                ('timesheet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='contracts.timesheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CHARGE', 'Employer Card Debit'), ('PAYOUT', 'Candidate Disbursement Transfer'), ('REFUND', 'Employer Refund')], max_length=20)),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack Ghana'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.contractinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
