# Generated by Django 6.1.1 on 2026-09-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_enabled', models.BooleanField(default=True, help_text='Enable/disable Paystack for candidate Mobile Money disbursements.', verbose_name='Paystack Enabled')),
                ('paystack_mode', models.CharField(choices=[('TEST', 'Test / Sandbox Mode'), ('LIVE', 'Live / Production Mode')], default='TEST', help_text='Operating mode: Test/Sandbox or Live/Production.', max_length=10, verbose_name='Paystack Environment')),
                ('paystack_public_key', models.CharField(blank=True, default='', help_text='Public API key from Paystack Dashboard (e.g. pk_test_... or pk_live_...).', max_length=255, verbose_name='Paystack Public Key')),
                ('paystack_secret_key', models.CharField(blank=True, default='', help_text='Secret API key from Paystack Dashboard (e.g. sk_test_... or sk_live_...). Used for authenticating transfer requests & HMAC webhook verification.', max_length=255, verbose_name='Paystack Secret Key')),
                ('flutterwave_enabled', models.BooleanField(default=True, help_text='Enable/disable Flutterwave for employer card payments and settlements.', verbose_name='Flutterwave Enabled')),
                ('flutterwave_mode', models.CharField(choices=[('TEST', 'Test / Sandbox Mode'), ('LIVE', 'Live / Production Mode')], default='TEST', help_text='Operating mode: Test/Sandbox or Live/Production.', max_length=10, verbose_name='Flutterwave Environment')),
                ('flutterwave_public_key', models.CharField(blank=True, default='', help_text='Public API key from Flutterwave Dashboard (e.g. FLWPUBK_TEST-... or FLWPUBK-...).', max_length=255, verbose_name='Flutterwave Public Key')),
                ('flutterwave_secret_key', models.CharField(blank=True, default='', help_text='Secret API key from Flutterwave Dashboard (e.g. FLWSECK_TEST-... or FLWSECK-...).', max_length=255, verbose_name='Flutterwave Secret Key')),
                ('flutterwave_encryption_key', models.CharField(blank=True, default='', help_text='Optional encryption key from Flutterwave Dashboard for card tokenization.', max_length=255, verbose_name='Flutterwave Encryption Key')),
                ('flutterwave_secret_hash', models.CharField(blank=True, default='', help_text="Secret hash entered in Flutterwave Dashboard settings to authenticate inbound webhooks via 'verif-hash' header.", max_length=255, verbose_name='Flutterwave Webhook Secret Hash')),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time.', verbose_name='Active Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway API Configuration',
                'verbose_name_plural': 'Payment Gateway API Configurations',
            },
        ),
    ]
