# Generated by Django 6.1.1 on 2026-09-29 09:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentgatewayconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('TIMESHEET_LOCK', 'Weekly Timesheet Lock (Sunday 23:59)'), ('FRIDAY_PAYOUT', 'Friday Batch Payout (Friday 09:00)')], max_length=30)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success / Warnings'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('items_evaluated', models.PositiveIntegerField(default=0)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('summary_message', models.TextField(blank=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('executed_by', models.ForeignKey(blank=True, help_text='Null for automated cron triggers, user for manual staff runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automation Execution Log',
                'verbose_name_plural': 'Automation Execution Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
