# Generated by Django 6.1.1 on 2026-09-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(default='Kodafriq Clinical Faculty', max_length=150)),
                ('description', models.TextField()),
                ('curriculum_overview', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills_covered', models.ManyToManyField(blank=True, related_name='training_programs', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed & Certified'), ('DROPPED', 'Withdrawn')], default='ENROLLED', max_length=25)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('final_assessment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrolments', to='accounts.candidateprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='training.trainingprogram')),
            ],
            options={
                'unique_together': {('program', 'candidate')},
            },
        ),
    ]
