# Generated by Django 6.1.1 on 2026-09-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(default=45, help_text='Estimated study duration in minutes')),
                ('content', models.TextField(help_text='Clinical guidelines, chart scenarios, and curriculum material')),
                ('key_takeaways', models.TextField(blank=True, help_text='Core clinical coding rules and guidelines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.trainingprogram')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('program', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='training.trainingenrolment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.programmodule')),
            ],
            options={
                'unique_together': {('enrolment', 'module')},
            },
        ),
    ]
