# Generated by Django 6.1.1 on 2026-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_programmodule_moduleprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='accreditation_statement',
            field=models.CharField(blank=True, default='CONTINUING CLINICAL EDUCATION & ACCREDITATION', help_text='Accreditation sub-banner on certificate', max_length=250),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='certificate_subtitle',
            field=models.CharField(blank=True, default='Certificate of Completion', help_text='Certificate main heading, e.g. Certificate of Completion', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='instructor_title',
            field=models.CharField(blank=True, default='Lead Clinical Faculty', help_text='Signatory title displayed on certificate', max_length=150),
        ),
    ]
