# Generated by Django 6.1.1 on 2026-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingprogram_accreditation_statement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_header_text', models.CharField(default='KODAFRIQ CLINICAL FACULTY', help_text='Header text on the top-left corner of the certificate', max_length=150)),
                ('signatory_name', models.CharField(default='Dr. Chioma Adeyemi, MD, CCS, CCDS', help_text='Signatory name (e.g. Lead Clinical Faculty personnel)', max_length=150)),
                ('signatory_title', models.CharField(default='Lead Clinical Faculty', help_text='Signatory title displayed beneath signature line', max_length=150)),
                ('signatory_signature_image', models.FileField(blank=True, help_text='Upload official signature image (transparent PNG recommended). If omitted, an elegant cursive script font is rendered.', null=True, upload_to='certificates/signatures/')),
                ('signatory_font_family', models.CharField(choices=[('Caveat', 'Caveat (Fluid Hand-drawn Script)'), ('Great Vibes', 'Great Vibes (Formal Calligraphy)'), ('Dancing Script', 'Dancing Script (Modern Script)'), ('Allura', 'Allura (Classic Elegance)')], default='Caveat', help_text='Cursive font family used when no signature image is uploaded', max_length=50)),
                ('organization_name', models.CharField(default='Kodafriq', help_text='Organization brand name displayed in header', max_length=100)),
                ('organization_logo', models.FileField(blank=True, help_text='Upload custom organization logo. If empty, the standard Kodafriq brand mark is used.', null=True, upload_to='certificates/logos/')),
                ('accreditation_badge_text', models.CharField(default='VERIFIED ACCREDITED CREDENTIAL', help_text='Accreditation badge in top-right corner', max_length=150)),
                ('accreditation_subtitle', models.CharField(default='CONTINUING CLINICAL EDUCATION & ACCREDITATION', help_text='Subtitle under the organization logo', max_length=200)),
                ('certificate_title', models.CharField(default='CERTIFICATE OF COMPLETION', help_text='Main heading on the certificate', max_length=150)),
                ('certifies_statement', models.CharField(default='This hereby certifies that', help_text="Introductory text before candidate's name", max_length=150)),
                ('fulfillment_statement', models.TextField(default='has successfully fulfilled all academic curriculum requirements, practical clinical coding audits, and quality standards for:', help_text='Curriculum completion statement before program title')),
                ('primary_border_color', models.CharField(default='#006fe6', help_text='Outer border color and primary brand accents (HEX or CSS color)', max_length=20)),
                ('secondary_border_color', models.CharField(default='#0284c7', help_text='Inner border accent and subtitle color (HEX or CSS color)', max_length=20)),
                ('seal_color', models.CharField(default='#10b981', help_text='Accredited circular seal border and shield color', max_length=20)),
                ('seal_background', models.CharField(default='#ecfdf5', help_text='Accredited circular seal background fill', max_length=20)),
                ('seal_title', models.CharField(default='VERIFIED', help_text='Text displayed in the circular security seal', max_length=50)),
                ('seal_subtitle', models.CharField(default='ACCREDITED', help_text='Subtext displayed in the circular security seal', max_length=50)),
                ('border_style', models.CharField(choices=[('double', 'Double Border (Classic Prestigious)'), ('solid', 'Solid Bold Border (Modern Minimal)'), ('groove', 'Grooved Border (Formal Academic)'), ('dual_frame', 'Dual Frame (Luxury Inset)')], default='double', help_text='Border framing style for the certificate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Design Configuration',
                'verbose_name_plural': 'Certificate Design Configuration',
            },
        ),
    ]
