# Generated by Django 6.1.1 on 2026-09-27 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_certificatetemplateconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Descriptive title (e.g., 'ICD-10-CM Official Coding Guidelines 2026', 'Clinical Audit Walkthrough Video')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief notes or instructions for students')),
                ('material_type', models.CharField(choices=[('DOCUMENT', 'Document (PDF, Word DOCX, Excel, Slides)'), ('VIDEO', 'Video Upload (MP4, WebM, MOV)'), ('VIDEO_EMBED', 'External Video Link (YouTube, Vimeo, Loom)'), ('AUDIO', 'Audio Lecture / Podcast (MP3, WAV)'), ('RESOURCE', 'Clinical Cheat Sheet / Guide'), ('EXTERNAL', 'External Clinical Reference URL')], default='DOCUMENT', help_text='Type of curriculum resource', max_length=25)),
                ('file', models.FileField(blank=True, help_text='Upload video (MP4), document (PDF, DOCX, XLSX, PPTX), or audio file', null=True, upload_to='training/materials/%Y/%m/')),
                ('external_url', models.URLField(blank=True, help_text='Direct URL if hosted externally (YouTube, Vimeo, Loom, Google Drive, AWS S3)')),
                ('is_downloadable', models.BooleanField(default=True, help_text='Allow enrolled candidates to download this file directly')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order sequence within the module/program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, help_text='Optional specific module this material belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='training.programmodule')),
                ('program', models.ForeignKey(blank=True, help_text='Associated training program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='training.trainingprogram')),
            ],
            options={
                'verbose_name': 'Training Material & Upload',
                'verbose_name_plural': 'Training Materials & Uploads',
                'ordering': ['order', 'id'],
            },
        ),
    ]
