# Generated by Django 6.1.1 on 2026-09-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('country', models.CharField(db_index=True, default='Unknown', max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(default='Desktop', max_length=30)),
                ('device_os', models.CharField(blank=True, max_length=60)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest Visit',
                'verbose_name_plural': 'Guest Visits',
                'ordering': ['-last_visited_at'],
            },
        ),
    ]
