# Generated by Django 6.1.1 on 2026-09-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage Configuration', max_length=100)),
                ('hero_background_image', models.ImageField(blank=True, help_text='Desktop hero background artwork (Recommended: 1920x1080 transparent or blended PNG/JPG). Leave blank for default.', null=True, upload_to='homepage/', verbose_name='Hero Desktop Artwork (Right Side Background)')),
                ('hero_mobile_image', models.ImageField(blank=True, help_text='Mobile hero visual image shown below the CTA on mobile devices. Leave blank for default.', null=True, upload_to='homepage/', verbose_name='Hero Mobile Visual Image')),
                ('ecosystem_image', models.ImageField(blank=True, help_text='Healthcare Talent Ecosystem visual image. Leave blank for default.', null=True, upload_to='homepage/', verbose_name='Ecosystem Section Doctor Visual')),
                ('trust_security_image', models.ImageField(blank=True, help_text='Trust by Design section image. Leave blank for default.', null=True, upload_to='homepage/', verbose_name='Trust & Security Section Visual')),
                ('partners_strip_image', models.ImageField(blank=True, help_text='Consolidated partner logos strip image (used if individual partner organizations are not added). Leave blank for default.', null=True, upload_to='homepage/', verbose_name='Partners Banner Strip Image (Fallback)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Image & Asset Settings',
                'verbose_name_plural': 'Homepage Image & Asset Settings',
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name (e.g. World Health Organization, Johns Hopkins, NHS)', max_length=150)),
                ('logo', models.ImageField(help_text='Upload partner logo (transparent PNG or SVG recommended)', upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text='Optional website link (makes logo clickable)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g. 1, 2, 3)')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner & Trusted Organization',
                'verbose_name_plural': 'Partners & Trusted Organizations',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
