# Generated by Django 6.1.1 on 2026-10-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagesetting_partnerorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Work / Contact Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number (Optional)')),
                ('inquiry_type', models.CharField(choices=[('employer', 'Healthcare Employer / Facility'), ('candidate', 'Healthcare Professional / Candidate'), ('partner', 'Institution / Strategic Partner'), ('general', 'General Inquiry / Support')], default='employer', max_length=40, verbose_name='Inquiry Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved / Followed Up')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL. Leave empty to hide on website.', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL. Leave empty to hide on website.', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Company/Organization LinkedIn profile or page URL. Leave empty to hide on website.', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X / Twitter profile URL. Leave empty to hide on website.', verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp contact or business link. Leave empty to hide on website.', verbose_name='WhatsApp URL'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel or video URL. Leave empty to hide on website.', verbose_name='YouTube URL'),
        ),
    ]
