# Generated by Django 6.1.1 on 2026-10-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinquiry_homepagesetting_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question title displayed on the homepage.', max_length=255)),
                ('answer', models.TextField(help_text='Detailed answer text. Supports standard text or paragraphs.')),
                ('category', models.CharField(choices=[('verification', 'Talent Verification & Credentialing'), ('employers', 'Employers & Hiring Process'), ('payments', 'Contracts & Milestone Payments'), ('security', 'Data Security & Compliance'), ('general', 'General Inquiries')], default='verification', help_text='Category group for organization.', max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g. 1, 2, 3...)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the homepage without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service')], help_text='Select whether this is the Privacy Policy or Terms of Service.', max_length=30, unique=True)),
                ('title', models.CharField(help_text='Page title displayed in the hero banner.', max_length=150)),
                ('slug', models.SlugField(help_text='URL slug (e.g. privacy-policy or terms-of-service).', max_length=60, unique=True)),
                ('last_updated_date', models.CharField(default='October 6, 2026', help_text='Text display of last revised date (e.g. October 6, 2026).', max_length=60)),
                ('summary', models.TextField(blank=True, help_text='High-level overview summary shown at the top of the legal document.')),
                ('content', models.TextField(help_text='Full legal content. Supports HTML markup (headings, paragraphs, lists, callout boxes).')),
                ('is_published', models.BooleanField(default=True, help_text='Toggle visibility on the website.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
            },
        ),
    ]
