# Generated by Django on 2026-10-06
from django.db import migrations

PRIVACY_HTML = '<div class="kf-legal-content-body">\n    <section id="section-1" class="kf-legal-section">\n        <h2>1. Introduction & Scope</h2>\n        <p>\n            Welcome to Kodafriq Data Management Solutions ("Kodafriq", "we", "our", or "us"). We provide a specialized \n            digital platform for healthcare talent verification, clinical credentialing, and employer matching across Africa \n            and globally.\n        </p>\n        <p>\n            This Privacy Policy applies to all individuals who access our website, create candidate or employer accounts, \n            submit credential documents, or interact with our services (collectively, the "Platform"). By using Kodafriq, you \n            acknowledge and consent to the data practices described herein.\n        </p>\n    </section>\n\n    <section id="section-2" class="kf-legal-section">\n        <h2>2. Information We Collect</h2>\n        <p>To deliver accurate healthcare talent credentialing and matching, we collect the following categories of data:</p>\n        <ul>\n            <li><strong>Identity & Contact Details:</strong> Full name, government-issued photo ID, date of birth, nationality, residential address, telephone number, and email address.</li>\n            <li><strong>Clinical Credentials & Licensure:</strong> Certified diplomas, medical degrees, official board licenses, ICD-10/CPT coding credentials (CPC, CCS, CIC), issuing authority registries, and credential verification numbers.</li>\n            <li><strong>Employment & Background History:</strong> Curriculum vitae, past healthcare employer references, clinical experience records, and verified background check disclosures.</li>\n            <li><strong>Technical & Telemetry Data:</strong> IP address, device operating system, browser specifications, login timestamps, and platform audit logs collected for security and fraud prevention.</li>\n            <li><strong>Financial & Transaction Details:</strong> Bank account numbers, payout routes, and escrow transaction histories (processed securely via regulated third-party payment gateways; we never store raw card security codes).</li>\n        </ul>\n    </section>\n\n    <section id="section-3" class="kf-legal-section">\n        <h2>3. How We Use Your Information</h2>\n        <p>We process your information under lawful legal bases for the following operational purposes:</p>\n        <ul>\n            <li><strong>Talent Verification & Credentialing:</strong> Validating the authenticity of healthcare qualifications, licenses, and coding certifications with official registry databases.</li>\n            <li><strong>Employer Matching:</strong> Presenting verified candidate profiles to prospective healthcare employers, hospitals, and clinical research facilities seeking qualified talent.</li>\n            <li><strong>Contract Execution & Milestone Escrow:</strong> Facilitating digital employment agreements, managing milestone deliverables, and executing verified Friday payouts.</li>\n            <li><strong>Platform Security & Compliance:</strong> Safeguarding accounts against unauthorized access, credential forgery, identity theft, and malicious cyber activity.</li>\n        </ul>\n    </section>\n\n    <section id="section-4" class="kf-legal-section">\n        <h2>4. Data Sharing & Third-Party Disclosures</h2>\n        <p>\n            <strong>Kodafriq does not sell, rent, or trade your personal data to advertisers or third parties.</strong> We only disclose information in strictly defined circumstances:\n        </p>\n        <ul>\n            <li><strong>Verified Employers & Healthcare Facilities:</strong> Once a healthcare candidate applies or agrees to be matched, their verified credentials and professional summary are made accessible to authorized healthcare employers.</li>\n            <li><strong>Official Licensing Boards & Verification Partners:</strong> We coordinate with accredited verification registries to authenticate clinical credentials.</li>\n            <li><strong>Escrow & Banking Partners:</strong> Information required to execute legitimate contract disbursements and milestone escrow releases.</li>\n            <li><strong>Legal & Regulatory Obligations:</strong> When mandated by applicable law, court order, or official healthcare regulatory directive.</li>\n        </ul>\n    </section>\n\n    <section id="section-5" class="kf-legal-section">\n        <h2>5. Security, Encryption & Healthcare Compliance</h2>\n        <div class="kf-legal-callout">\n            <div class="kf-legal-callout-icon">\n                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22">\n                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>\n                </svg>\n            </div>\n            <div>\n                <strong>Healthcare-Grade Security Standards</strong>\n                <p>All sensitive documents, credential certificates, and transactional records are encrypted using AES-256 at rest and TLS 1.3 in transit.</p>\n            </div>\n        </div>\n        <p>\n            We implement stringent role-based access control (RBAC), multi-factor authentication for administrative staff, \n            continuous server monitoring, and immutable audit logs tracking every administrative review of personal data.\n        </p>\n    </section>\n\n    <section id="section-6" class="kf-legal-section">\n        <h2>6. Data Retention & Storage</h2>\n        <p>\n            We retain personal and credentialing data for as long as your account remains active or as required to fulfill legal, \n            regulatory, and audit requirements. If you request account closure, we securely anonymize or delete your records, \n            subject to statutory healthcare record retention mandates.\n        </p>\n    </section>\n\n    <section id="section-7" class="kf-legal-section">\n        <h2>7. Your Rights & Choices</h2>\n        <p>Depending on your jurisdiction, you possess the following rights regarding your personal information:</p>\n        <ul>\n            <li><strong>Right of Access:</strong> Request a copy of the personal and verification data we maintain on your profile.</li>\n            <li><strong>Right of Rectification:</strong> Request correction of inaccurate, outdated, or incomplete credentials.</li>\n            <li><strong>Right to Erasure:</strong> Request deletion of your personal data where retention is no longer legally justified.</li>\n            <li><strong>Right to Restrict Processing:</strong> Request restrictions on how your profile is displayed or matched.</li>\n            <li><strong>Data Portability:</strong> Obtain your verified skills and credentials in a portable, structured digital format.</li>\n        </ul>\n    </section>\n\n    <section id="section-8" class="kf-legal-section">\n        <h2>8. Contact Our Data Protection Office</h2>\n        <p>\n            If you have questions, inquiries, or wish to exercise any of your privacy rights, please reach out directly to our \n            Data Protection Team:\n        </p>\n        <div class="kf-legal-contact-box">\n            <p><strong>Kodafriq Data Management Solutions - Privacy & Compliance Office</strong></p>\n            <p>Email: <a href="mailto:privacy@kodafriq.com">privacy@kodafriq.com</a> &bull; <a href="mailto:support@kodafriq.com">support@kodafriq.com</a></p>\n            <p>Website: <a href="https://kodafriq.com">https://kodafriq.com</a></p>\n        </div>\n    </section>\n</div>'
TERMS_HTML = '<div class="kf-legal-content-body">\n    <section id="section-1" class="kf-legal-section">\n        <h2>1. Acceptance of Terms</h2>\n        <p>\n            These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "Candidate", or "Employer") \n            and Kodafriq Data Management Solutions ("Kodafriq", "we", "our", or "us"). By accessing our website, registering an account, \n            or using our verification and matching tools, you confirm that you have read, understood, and agree to these Terms.\n        </p>\n    </section>\n\n    <section id="section-2" class="kf-legal-section">\n        <h2>2. Scope of Kodafriq Platform Services</h2>\n        <p>\n            Kodafriq operates a digital healthcare talent verification, clinical credentialing, and employer-matching network. \n            We specialize in Health Information Management (HIM), Certified Medical Coding (CPC, CCS, CIC, COC), Medical Billing, \n            Revenue Cycle Management (RCM), and clinical support professionals.\n        </p>\n        <div class="kf-legal-callout">\n            <div class="kf-legal-callout-icon">\n                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22">\n                    <circle cx="12" cy="12" r="10"></circle>\n                    <line x1="12" y1="8" x2="12" y2="12"></line>\n                    <line x1="12" y1="16" x2="12.01" y2="16"></line>\n                </svg>\n            </div>\n            <div>\n                <strong>Platform Disclaimer</strong>\n                <p>Kodafriq authenticates credentials and matches talent with healthcare organizations. Kodafriq is not a healthcare provider, hospital, or medical diagnostic facility and does not provide direct medical advice.</p>\n            </div>\n        </div>\n    </section>\n\n    <section id="section-3" class="kf-legal-section">\n        <h2>3. Account Registration & Security</h2>\n        <p>\n            To use key features of the platform, you must register as either a Healthcare Candidate or an Employer. \n            You agree to provide true, accurate, and complete information during onboarding and to maintain the security of your \n            credentials. You are solely responsible for all activities occurring under your account.\n        </p>\n    </section>\n\n    <section id="section-4" class="kf-legal-section">\n        <h2>4. Healthcare Professional Obligations</h2>\n        <p>As a healthcare professional utilizing Kodafriq, you represent, warrant, and agree that:</p>\n        <ul>\n            <li>All diplomas, certifications, medical board licenses, and work experience provided are authentic and unencumbered.</li>\n            <li>You will immediately notify Kodafriq if your license is suspended, restricted, or subject to disciplinary review by any medical authority.</li>\n            <li>You will perform all contracted healthcare services in adherence to standard clinical ethics, HIPAA privacy guidelines, and professional quality standards.</li>\n            <li>You will not misrepresent your skills, credentials, or assessment scores.</li>\n        </ul>\n    </section>\n\n    <section id="section-5" class="kf-legal-section">\n        <h2>5. Employer & Healthcare Facility Obligations</h2>\n        <p>As an employer or healthcare facility utilizing Kodafriq, you agree that:</p>\n        <ul>\n            <li>You will provide clear, truthful job descriptions and defined contract scopes of work.</li>\n            <li>You will promptly review submitted deliverables, timesheets, and milestone accomplishments in good faith.</li>\n            <li>You will fund contract milestone escrow accounts before candidate onboarding and release payments upon milestone completion.</li>\n            <li>You will maintain safe, compliant, and lawful work arrangements for all engaged professionals.</li>\n        </ul>\n    </section>\n\n    <section id="section-6" class="kf-legal-section">\n        <h2>6. Milestone Escrow & Payout Protection</h2>\n        <p>\n            To protect both employers and healthcare talent, Kodafriq utilizes a secure milestone escrow structure:\n        </p>\n        <ul>\n            <li><strong>Escrow Funding:</strong> Employers deposit funds into escrow corresponding to agreed contract milestones or bi-weekly pay cycles.</li>\n            <li><strong>Milestone Approval:</strong> Upon submission of completed coding batches, billing cycles, or hours, employers have a standard review window (7 business days) to accept or request revision.</li>\n            <li><strong>Dispute Resolution:</strong> If a disagreement arises regarding milestone fulfillment, either party may escalate to Kodafriq Operations Officers for independent mediation.</li>\n        </ul>\n    </section>\n\n    <section id="section-7" class="kf-legal-section">\n        <h2>7. Non-Circumvention & Off-Platform Conduct</h2>\n        <p>\n            For a period of 12 months following initial introduction on Kodafriq, employers and candidates agree to conduct all \n            contractual relationships, billing, and compensation through the Kodafriq platform, unless an agreed enterprise buyout \n            fee is remitted. Bypassing platform escrow undermines verification, audit trails, and financial protections.\n        </p>\n    </section>\n\n    <section id="section-8" class="kf-legal-section">\n        <h2>8. Intellectual Property</h2>\n        <p>\n            All trademarks, logos, visual branding, user interface designs, algorithms, and proprietary software comprising \n            Kodafriq are the exclusive intellectual property of Kodafriq Data Management Solutions. Users may not copy, reverse \n            engineer, scrape, or distribute platform assets without prior written consent.\n        </p>\n    </section>\n\n    <section id="section-9" class="kf-legal-section">\n        <h2>9. Termination & Account Suspension</h2>\n        <p>\n            Kodafriq reserves the right to suspend or terminate accounts that violate these Terms, provide fraudulent credential \n            documents, fail verification audits, engage in off-platform circumvention, or act in a manner detrimental to patients, \n            employers, or platform integrity.\n        </p>\n    </section>\n\n    <section id="section-10" class="kf-legal-section">\n        <h2>10. Limitation of Liability</h2>\n        <p>\n            To the maximum extent permitted by applicable law, Kodafriq shall not be liable for indirect, incidental, special, \n            consequential, or punitive damages arising out of your access to or inability to use the platform. Our aggregate \n            liability shall not exceed the total fees received by Kodafriq in connection with your account during the six (6) \n            months preceding the claim.\n        </p>\n    </section>\n\n    <section id="section-11" class="kf-legal-section">\n        <h2>11. Contact & Legal Notices</h2>\n        <p>\n            For legal inquiries, notices, or clarifications regarding these Terms of Service, please contact:\n        </p>\n        <div class="kf-legal-contact-box">\n            <p><strong>Kodafriq Data Management Solutions - Legal Department</strong></p>\n            <p>Email: <a href="mailto:legal@kodafriq.com">legal@kodafriq.com</a> &bull; <a href="mailto:support@kodafriq.com">support@kodafriq.com</a></p>\n            <p>Website: <a href="https://kodafriq.com">https://kodafriq.com</a></p>\n        </div>\n    </section>\n</div>'

def seed_legal_and_faqs(apps, schema_editor):
    LegalPage = apps.get_model('core', 'LegalPage')
    FAQItem = apps.get_model('core', 'FAQItem')

    # 1. Seed Privacy Policy
    if not LegalPage.objects.filter(page_type='privacy').exists():
        LegalPage.objects.create(
            page_type='privacy',
            title='Privacy Policy',
            slug='privacy-policy',
            last_updated_date='October 6, 2026',
            summary=(
                "At Kodafriq Data Management Solutions ('Kodafriq'), we respect your privacy and are committed "
                "to safeguarding the personal, credentialing, and sensitive information entrusted to us by healthcare "
                "professionals, healthcare facilities, and partner institutions. This Privacy Policy details our data "
                "practices, security safeguards, and your legal rights under international data protection standards."
            ),
            content=PRIVACY_HTML,
            is_published=True
        )

    # 2. Seed Terms of Service
    if not LegalPage.objects.filter(page_type='terms').exists():
        LegalPage.objects.create(
            page_type='terms',
            title='Terms of Service',
            slug='terms-of-service',
            last_updated_date='October 6, 2026',
            summary=(
                "These Terms of Service govern your access to and usage of the Kodafriq Data Management Solutions platform. "
                "By registering an account, verifying credentials, posting healthcare opportunities, or executing contracts, "
                "you agree to be legally bound by these conditions."
            ),
            content=TERMS_HTML,
            is_published=True
        )

    # 3. Seed FAQ Items
    if not FAQItem.objects.exists():
        faqs = [
            (
                "How does healthcare candidate verification work on Kodafriq?",
                (
                    "Kodafriq implements a multi-stage credentialing and verification pipeline: government-issued ID validation, "
                    "clinical education & professional license authentication directly with official health regulatory boards, "
                    "verified employment background checks, and objective proctored assessments in medical coding (ICD-10-CM/PCS, CPT, HCPCS), "
                    "billing, or revenue cycle management."
                ),
                "verification",
                1
            ),
            (
                "Why do newly registered candidates start with a base score and how is verification calculated?",
                (
                    "Upon completing initial registration and identity onboarding, candidates start with a 60% foundation score. "
                    "As candidates verify credentials, upload certifications, complete technical assessments, and gain client reviews, "
                    "their verification score dynamically climbs toward 100% verified status."
                ),
                "verification",
                2
            ),
            (
                "What healthcare specialties and roles are supported on the platform?",
                (
                    "Our specialized talent pool covers Health Information Management (HIM), Certified Medical Coding (CPC, CCS, CIC, COC), "
                    "Medical Billing & Claims Adjudication, Revenue Cycle Management (RCM), Clinical Documentation Improvement (CDI), and "
                    "Telehealth Clinical Support."
                ),
                "verification",
                3
            ),
            (
                "How quickly can healthcare employers hire and deploy talent?",
                (
                    "Because candidates in our talent pool are pre-vetted and credentialed, healthcare facilities and employers typically "
                    "review candidate profiles, schedule interviews, and finalize digital contracts within 48 to 72 hours, reducing traditional "
                    "healthcare hiring cycles by over 60%."
                ),
                "employers",
                4
            ),
            (
                "How does milestone escrow and payment protection work?",
                (
                    "All contract funds are held securely in milestone escrow. Payments are released according to agreed milestones or scheduled "
                    "bi-weekly payouts upon employer sign-off. This ensures total financial transparency, automated audit receipts, and dispute mediation "
                    "protection for both parties."
                ),
                "payments",
                5
            ),
            (
                "Is Kodafriq compliant with healthcare data security and privacy standards?",
                (
                    "Yes. We adhere strictly to international healthcare privacy standards and HIPAA-aligned security protocols. Our infrastructure "
                    "features end-to-end 256-bit encryption in transit and at rest, granular role-based access control, and complete audit trails for every "
                    "platform action."
                ),
                "security",
                6
            ),
        ]
        for q, a, cat, order in faqs:
            FAQItem.objects.create(
                question=q,
                answer=a,
                category=cat,
                display_order=order,
                is_active=True
            )

def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faqitem_legalpage'),
    ]

    operations = [
        migrations.RunPython(seed_legal_and_faqs, noop_reverse),
    ]
