# Generated by Django 6.1.1 on 2026-10-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_legal_and_faq_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Announcement title (e.g. 'Kodafriq Official Platform Launch').", max_length=200)),
                ('eyebrow_badge', models.CharField(default='OFFICIAL LAUNCH EVENT', help_text="Small pill tag displayed above title (e.g. 'OFFICIAL LAUNCH EVENT', 'LIVE TODAY', 'NEW UPDATE').", max_length=80)),
                ('headline', models.CharField(blank=True, help_text="Subheading or slogan (e.g. 'Global Healthcare Talent Without Borders – Connecting skilled professionals with global opportunities').", max_length=255)),
                ('body_text', models.TextField(blank=True, help_text='Detailed announcement description, agenda, or highlights. Supports multiple paragraphs.')),
                ('event_datetime', models.DateTimeField(blank=True, help_text='Exact scheduled date & time of the event (optional, used for countdown / badges).', null=True)),
                ('event_datetime_text', models.CharField(blank=True, default='Saturday, 10 October 2026 • 5:00 PM UK / 4:00 PM GHANA', help_text='Human-readable event date/time string displayed to users.', max_length=150)),
                ('event_location_text', models.CharField(blank=True, default='Online (Google Meet)', help_text="Event venue or format (e.g. 'Online (Google Meet)', 'Virtual Broadcast').", max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Primary flyer or event poster (e.g. Official Launch Agenda flyer).', null=True, upload_to='announcements/', verbose_name='Primary Image / Flyer')),
                ('secondary_image', models.ImageField(blank=True, help_text='Optional secondary poster (e.g. Keynote Speakers flyer). When provided, users can switch between flyers in the modal.', null=True, upload_to='announcements/', verbose_name='Secondary Image / Flyer')),
                ('image_alt_text', models.CharField(blank=True, default='Kodafriq Launch Event Flyer', help_text='Accessibility alt text for the images.', max_length=200)),
                ('primary_action_text', models.CharField(blank=True, default='Join Launch Meeting', help_text="Text for primary button (e.g. 'Join Launch Meeting', 'Join Us Live Online').", max_length=80)),
                ('primary_action_url', models.URLField(blank=True, default='https://calendar.app.google/ox5GwEg89EsPeYJ39', help_text='Link for primary button (e.g. Google Meet link, Google Calendar event link).')),
                ('primary_action_new_tab', models.BooleanField(default=True, help_text='Open primary action link in a new browser tab.')),
                ('secondary_action_text', models.CharField(blank=True, default='Register as Candidate', help_text="Optional secondary button text (e.g. 'Register as Candidate', 'Explore Platform').", max_length=80)),
                ('secondary_action_url', models.CharField(blank=True, default='/accounts/register/candidate/', help_text='Optional secondary link (can be internal URL like /accounts/register/candidate/ or external URL).', max_length=255)),
                ('target_placement', models.CharField(choices=[('both', 'Both Homepage and Dashboards'), ('homepage', 'Homepage Only'), ('dashboard', 'Dashboards Only')], default='both', help_text='Where this announcement will be displayed.', max_length=20)),
                ('display_mode', models.CharField(choices=[('both', 'Both Top Banner & Modal Popup'), ('popup', 'Modal Popup Dialog Only'), ('banner', 'Top Banner Only')], default='both', help_text='Choose whether this appears as a Top Banner, a Modal Popup, or Both.', max_length=20)),
                ('content_format', models.CharField(choices=[('full', 'Full Rich Combo (Images, Text, Details & Action Links)'), ('images_only', 'Image / Flyer Only (Full Visual)'), ('images_with_links', 'Image / Flyer with Action Links'), ('text_only', 'Text Only (No Images, with/without Links)'), ('text_with_links', 'Text with Action Links Only'), ('text_with_images', 'Text with Images (No Action Links)')], default='full', help_text='Structure of the announcement: Just text, text + links, text + images, image only, image + links, or full combo.', max_length=20)),
                ('popup_trigger_type', models.CharField(choices=[('delay', 'Stay Duration Delay (Pops up after visitor stays on page)'), ('random_interval', 'Random Time Intervals (Pops up periodically at random intervals)'), ('immediate', 'Immediate (Pops up immediately on page load)')], default='delay', help_text='When/how the modal popup triggers: after staying on page, at random time intervals, or immediately.', max_length=20)),
                ('popup_delay_seconds', models.PositiveIntegerField(default=3, help_text="For 'Stay Duration': seconds after page load before the modal pops up (e.g. 3 or 5 seconds).")),
                ('random_min_interval_seconds', models.PositiveIntegerField(default=20, help_text="For 'Random Intervals': minimum seconds before the popup triggers.")),
                ('random_max_interval_seconds', models.PositiveIntegerField(default=60, help_text="For 'Random Intervals': maximum seconds before the popup triggers.")),
                ('allow_dismiss', models.BooleanField(default=True, help_text='Allow users to dismiss/close the popup.')),
                ('remember_dismissal_hours', models.PositiveIntegerField(default=0, help_text='Hours to keep modal closed after user dismisses it (0 = re-check on new page/session or interval).')),
                ('is_active', models.BooleanField(default=True, help_text='Master switch: Check to turn ON announcement, uncheck to turn OFF immediately at any time.')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Optional auto-start schedule date/time (leave empty to show immediately).', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Optional auto-expire date/time (leave empty to show indefinitely until turned off).', null=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Higher priority announcements display before lower priority ones if multiple are active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Announcement & Launch Event',
                'verbose_name_plural': 'Platform Announcements & Launch Events',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
