# Generated by Django 6.1.1 on 2026-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='rate_negotiable',
            field=models.BooleanField(default=False, help_text='Indicates rate negotiation interest for this candidate'),
        ),
    ]
