# Generated by Django 6.1.1 on 2026-09-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_shortlist_rate_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='is_shortlisted',
            field=models.BooleanField(default=True, help_text='Indicates candidate is in employer saved talent pool'),
        ),
    ]
