# Generated by Django 6.1.1 on 2026-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_shortlist_is_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Resume submitted for this specific application (defaults to candidate profile resume if not overridden)', null=True, upload_to='applications/resumes/'),
        ),
    ]
