# Generated by Django 6.1.1 on 2026-09-12 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='activity', help_text='Icon identifier for UI', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code_standard', models.CharField(blank=True, help_text='e.g., ICD-10-CM, CPT, HCPCS, DRG, RCM', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('ASSESSED', 'Assessed'), ('KODAFRIQ_VERIFIED', 'Kodafriq Verified')], default='SELF_REPORTED', max_length=25)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner / Foundational'), ('INTERMEDIATE', 'Intermediate / Competent'), ('ADVANCED', 'Advanced / Proficient'), ('EXPERT', 'Subject Matter Expert')], default='INTERMEDIATE', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='skills/evidence/')),
                ('evidence_notes', models.TextField(blank=True, help_text='Description of supporting evidence')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.candidateprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skills', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_instances', to='skills.skill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
            },
        ),
    ]
