# Generated by Django 6.1.1 on 2026-09-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification Only'), ('EMAIL', 'Email Broadcast Only'), ('BOTH', 'Both In-App & Email')], default='IN_APP', help_text='Delivery channel for this communication', max_length=20)),
                ('target_type', models.CharField(choices=[('SINGLE_USER', 'Single Specific User'), ('MULTIPLE_USERS', 'Multiple Specific Users'), ('ALL_EMPLOYERS', 'All Employers'), ('ALL_PROFESSIONALS', 'All Healthcare Professionals (Candidates)'), ('ALL_ADMINS', 'All Administrators & Staff'), ('ALL_USERS', 'All Platform Users'), ('GROUP', 'Django User Group')], default='ALL_USERS', help_text='Target audience category', max_length=30)),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'Platform Announcement'), ('SECURITY', 'Security & Account Notice'), ('URGENT', 'Urgent Critical Alert'), ('JOB_MATCH', 'Job Opportunity Alert'), ('ASSESSMENT', 'Clinical Assessment Notice'), ('CERTIFICATE', 'Training & Certification Notice'), ('GENERAL', 'General Communication')], default='SYSTEM', help_text='Classification for styling and icon', max_length=30)),
                ('title', models.CharField(max_length=255, verbose_name='Subject / Title')),
                ('message', models.TextField(verbose_name='Message / Body Content')),
                ('action_url', models.CharField(blank=True, help_text='Optional link target for in-app click or email CTA button', max_length=500, verbose_name='Action Link (URL)')),
                ('action_button_text', models.CharField(blank=True, default='View Details', max_length=80, verbose_name='Action Button Label')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, help_text='Target Django auth group if target_type is GROUP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_broadcasts', to='auth.group')),
                ('target_users', models.ManyToManyField(blank=True, help_text='Target users if single or multiple users are selected', related_name='targeted_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Broadcast',
                'verbose_name_plural': 'Notification Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Delivered'), ('FAILED', 'Delivery Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to=settings.AUTH_USER_MODEL)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notificationbroadcast')),
            ],
            options={
                'verbose_name': 'Broadcast Delivery Log',
                'verbose_name_plural': 'Broadcast Delivery Logs',
                'ordering': ['-delivered_at'],
            },
        ),
    ]
