# Generated by Django 6.1.1 on 2026-09-21 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbroadcast',
            name='target_single_user',
            field=models.ForeignKey(blank=True, help_text='Select a recipient if target audience is Single Specific User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_targeted_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Target Single User'),
        ),
    ]
